# Generated by Django 2.0 on 2018-02-23 17:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trump', models.SmallIntegerField(default=1)),
                ('hand01', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('hand02', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('hand03', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('hand04', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('next_move', models.IntegerField(blank=True, choices=[(1, 'hand01'), (2, 'hand02'), (3, 'hand03'), (4, 'hand04')], default=1, null=True)),
            ],
        ),
    ]
