# Generated by Django 2.0 on 2018-02-23 17:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='moves',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
