# Generated by Django 2.0 on 2018-02-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_deck_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='moves',
        ),
    ]
